### ISSUE TITLE
怎么编译呢，能不能做个Makefile呢

### ISSUE THREAD

**Issue by daimon99** [sonichy/KuGou#2]

**Comment by sonichy** [comment]
我是用 Qt Creator 编译的，你这样编译：
qmake 项目名称.pro
make(unix or linux) or nmake(windows)

**Comment by daimon99** [comment]
好啦。真好用！
我装了一个qt，然后 用qtcreator打开，再编译，就好了。

**Comment by 178me** [comment]
我使用qtcreator打开编译  报错Unknown module(s) in QT: multimedia multimediawidgets

**Comment by 178me** [comment]
搜索了几个帖子 https://blog.csdn.net/gaoxiaochuan89/article/details/82632356

**Comment by sonichy** [comment]
sudo apt-get install libqt5multimedia5 libqt5multimediawidgets5

**Comment by 178me** [comment]
已解决 我下载了对应的模块
