### ISSUE TITLE
已经无法抓取歌曲

### ISSUE THREAD

**Issue by 178me** [sonichy/KuGou#4]
如果可以，非常希望维护一下

**Comment by sonichy** [comment]
哦豁，换API了？

**Comment by 178me** [comment]
你很久没有用了吗 大佬

**Comment by 178me** [comment]
我在网上找到这个酷狗音乐API，希望对你有帮助
   https://messoer.github.io/mess-api-doc/#/music/kugou?id=%e8%8e%b7%e5%8f%96%e9%9f%b3%e4%b9%90%e8%af%a6%e6%83%85

**Comment by sonichy** [comment]
刚才试了，没有问题啊，你确定会玩？

**Comment by 178me** [comment]
我这边可以搜索的到歌曲，但是播放不了 包括MV

**Comment by sonichy** [comment]
奇怪了，你可以从终端运行，看调试信息。
